### ISSUE TITLE
-corner and -side

### ISSUE THREAD

**Issue by Ralle** [Strilanc/Wc3PowerTowers#2]
In the quest log the -corner and -side commands have each other's descriptions.

Love the map, huge fan. Can I upload it on The Hive Workshop? Could you make an account and do it yourself?

**Comment by Strilanc** [comment]
Haha, you're right; they're switched.

I'm going to leave it as is, because this repo is really more for historical "what did I make then" purposes rather than active development.

(Also the source files in the repo aren't part of the build process used to generate the map. I always edited things directly in the newgen editor, so the source files are actually just copy-pastes of each trigger's content.)

You can upload the map wherever you want, and modify it however you want.
